# The URL the site will be built for
base_url = "https://malek4522.github.io/MalekZone/"
theme = "duckling"
title = "MALEK452"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Define site taxonomies used in content front matter
taxonomies = [{ name = "tags", feed = true }]
 

[markdown]

[markdown.highlighting]
style = "inline"
theme = "one-dark-pro"

[extra]
# Put all your custom variables here
default_theme = "dark"

show_reading_time = true
show_copy_button = true

accent_color = "#ff7800"
accent_color_dark = "#ffa348"

emoji_favicon = "🦉"


[extra.nav]
links = [
	{ url = "@/_index.md", name = "About me" },
	{ url = "@/blog/_index.md", name = "Blogs" },
	{ url = "@/contact/index.md", name = "Contact me" },
]

[extra.footer]
links = [
	{ url = "@/_index.md", name = "About me" },
	{ url = "@/blog/_index.md", name = "Blogs" },
	{ url = "@/contact/index.md", name = "Contact me" },
]


show_copyright = true
toc_inline = true
toc_ordered = true
show_backlinks = true
toc = true
katex = true
